document.writeln("<footer>");
document.writeln("        <div class=\"container\">");
document.writeln("            <div class=\"inner\">");
document.writeln("                <div class=\"footer_nav\">");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\"index.html\">首页</a></li>");
document.writeln("                        <li><i class=\"header_icon1\">|</i></li>");
document.writeln("                        <li><a href=\"company.html\">公司概况</a></li>");
document.writeln("                        <li><i class=\"header_icon1\">|</i></li>");
document.writeln("                        <li><a href=\"limits.html\">营业范围</a></li>");
document.writeln("                        <li><i class=\"header_icon1\">|</i></li>");
document.writeln("                        <li><a href=\"purpose.html\">服务宗旨</a></li>");
document.writeln("                        <li><i class=\"header_icon1\">|</i></li>");
document.writeln("                        <li><a href=\"future.html\">展望未来</a></li>");
document.writeln("                        <li><i class=\"header_icon1\">|</i></li>");
document.writeln("                        <li><a href=\"news.html\">新闻中心</a></li>");
document.writeln("                        <li><i class=\"header_icon1\">|</i></li>");
document.writeln("                        <li><a href=\"contact.html\">联系我们</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\"footer_content\">");
document.writeln("                    <div class=\"footer_content_left\">");
document.writeln("                        <ul>");
document.writeln("                            <li>电话：400-9020-778   0311-68023211</li>");
document.writeln("                            <li>邮编：050000</li>");
document.writeln("                            <li>邮箱：2200303430@qq.com</li>");
document.writeln("                            <li>地址：河北省石家庄市裕华东路49号天银广场1106室</li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"footer_content_right\">");
document.writeln("                        <img src=\"images/erweima_03.png\" alt=\"\">");
document.writeln("                        <p>关注官方微信</p>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\"footer_bottom\">");
document.writeln("                    <div class=\"copyright\">Copyright 2017-2020 河北邦源节能科技有限公司</div>");
document.writeln("                    <div class=\"beian_num\">ICP备案号：冀ICP备17013423号</div>");
document.writeln("                    <div class=\"yd\">技术支持：<a href=\"http://www.xinwangluo.net/\" target=\"_blank\" rel=\"noopener noreferrer\">有度网络</a></div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </footer>");