document.writeln(" <header>");
document.writeln("        <div class=\"container\">");
document.writeln("            <div class=\"header_content\">");
document.writeln("                <div class=\"log\">");
document.writeln("                    <img src=\"images/log.png\" alt=\"\">");
document.writeln("                </div>");
document.writeln("                <nav>");
document.writeln("                    <ul>");
document.writeln("                        <li><a class=\"nav_active\" href=\"index.html\">首页</a></li>");
document.writeln("                        <li><i class=\"header_icon\"></i></li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\"company.html\">公司概况</a>");
document.writeln("                            <div class=\"nav_hidden\">");
document.writeln("                                <ul class=\"nav_company\">");
document.writeln("                                    <li><a href=\"company.html\">公司简介</a></li>");
document.writeln("                                    <li><a href=\"intelligence.html\">企业资质</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li><i class=\"header_icon\"></i></li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\"limits.html\">营业范围</a>");
document.writeln("                            <div class=\"nav_hidden\">");
document.writeln("                                <ul class=\"nav_limits\">");
document.writeln("                                    <li><a href=\"limits.html\">景观照明</a></li>");
document.writeln("                                    <li><a href=\"limits.html\">建筑照明</a></li>");
document.writeln("                                    <li><a href=\"limits.html\">智慧照明</a></li>");
document.writeln("                                    <li><a href=\"limits.html\">室内照明</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li><i class=\"header_icon\"></i></li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\"purpose.html\">服务宗旨</a>");
document.writeln("                            <div class=\"nav_hidden\">");
document.writeln("                                <ul class=\"nav_purpose\">");
document.writeln("                                    <li><a href=\"server_tx.html\">服务体系</a></li>");
document.writeln("                                    <li><a href=\"server_sj.html\">设计服务</a></li>");
document.writeln("                                    <li><a href=\"server_gc.html\">工程服务</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li><i class=\"header_icon\"></i></li>");
document.writeln("                        <li><a href=\"future.html\">展望未来</a></li>");
document.writeln("                        <li><i class=\"header_icon\"></i></li>");
document.writeln("                        <li><a href=\"news.html\">新闻中心</a></li>");
document.writeln("                        <li><i class=\"header_icon\"></i></li>");
document.writeln("                        <li><a href=\"contact.html\">联系我们</a></li>");
document.writeln("                    </ul>");
document.writeln("                </nav>");
document.writeln("                <div class=\"header_tel\">");
document.writeln("                    <div class=\"header_tel_pic\">");
document.writeln("                        <img src=\"images/header_tel_03.png\" alt=\"\">");
document.writeln("                    </div>");
document.writeln("                    <div class=\"header_tel_txt\">");
document.writeln("                        <p>服务咨询热线</p>");
document.writeln("                        <p class=\"header_tel_num\">400-9020-778</p>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");